### ISSUE TITLE
re-release on PyPI

### ISSUE THREAD

**Issue by awesomebytes** [ros-infrastructure/superflore#152]
There have been quite a few fixes I'd say, why not re-release on PyPI?

**Comment by allenh1** [comment]
I'm waiting on #151 to get merged before I re-release, but I definitely plan to do that soon.

**Comment by allenh1** [comment]
@tfoote Please release version 0.3.0 on pypi!

**Comment by tfoote** [comment]
Uploaded with one small change #221

**Comment by awesomebytes** [comment]
Wohoo, thanks!
