### ISSUE TITLE
Remove ROS 2 index

### ISSUE THREAD

**Issue by allenh1** [ros-infrastructure/superflore#162]
In response to ros-infrastructure/rosindex#136, and in preparation for ROS 3 (just kidding), I'd like to remove the hardcoded logic that adds the ROS 2 index for Gentoo.

@tfoote I'm interested in adding an argument that would support a second ROS index (in case people want to override it), but I think that the logic can be completely replaced by the user just setting the variable for themselves. Does this make sense to you?

**Comment by tfoote** [comment]
Yeah, the user can always set their ROSDISTRO_INDEX_URL to select an alternative rosdistro index, such as a custom one.
