### ISSUE TITLE
quicker iteration

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [ros-infrastructure/superflore#20]
Will be super useful to have the packages regenerated (or at least one sample package) at every commit (like travisCI)

**Comment by allenh1** [comment]
@tfoote and I have been discussing working on integrating this system into the build farm. But, it's not quite ready (as exhibited by the fact that Travis probably hates me at this point).

> (or at least one sample package) at every commit 

This sounds like a really good idea to me. Do you want to work on that?

**Comment by Alessandro-Barbieri** [comment]
Using an eclass does not require to regenerate all the packages after every change

**Comment by allenh1** [comment]
@Alessandro-Barbieri Writing an eclass is somewhere down the line on my todo list. I can't spend time on it right now, but this is a plan for the future.

In the mean time, would you mind adapting the CI to show a sample ebuild?

**Comment by aballier** [comment]
> @Alessandro-Barbieri Writing an eclass is somewhere down the line on my todo list. I can't spend time on it right now, but this is a plan for the future.

Why don't you just simply copy ros-catkin.eclass, try to use it, make the changes you need, and poke me about what you need there so that we can start merging stuff to the main tree?

**Comment by allenh1** [comment]
@aballier That sounds quite reasonable

**Comment by allenh1** [comment]
I don't think this is relevant recently, as we've adopted the eclass approach, so I'm going to close this.
