### ISSUE TITLE
Change how platform packages without a mapping in rosdep/*.yaml are handled for OpenEmbedded

### ISSUE THREAD

**Issue by herb-kuta-lge** [ros-infrastructure/superflore#223]
Change how platform packages without a mapping in `rosdep/*.yaml` are handled for OpenEmbedded so that it's possible to specify all of the mappings that **bitbake** requires in order to parse the metadata for a particular recipe without having to rerun **superflore** multiple times.

**Comment by herb-kuta-lge** [comment]
Do this by having **superflore** use `${ROS_UNRESOLVED_PLATFORM_PKG_<PLATFORM_PKG>}` as the mapped value and adding assignments of the form `ROS_UNRESOLVED_PLATFORM_PKG_<PLATFORM_PKG> = "UNRESOLVED-<PLATFORM_PKG>"` to `conf/ros-distro/include/<ROS_DISTRO>/generated-ros-distro.inc`. These assignments are then overridden in `conf/ros-distro/include/<ROS_DISTRO>/ros-distro.inc` until the `rosdep/*.yaml` are updated and  **superflore** rerun.

**superflore** will no longer use the OpenEmbedded Layer Index to guess mappings.

**Comment by herb-kuta-lge** [comment]
This change has been incorporated into [revision 40](https://github.com/ros/meta-ros/wiki/Superflore-OE-Recipe-Generation-Scheme#revision-40) of the Superflore OE Recipe Generation Scheme wiki page.

**Comment by shr-project** [comment]
Fixed by https://github.com/ros-infrastructure/superflore/pull/232
