### ISSUE TITLE
superflore-gen-oe-recipes: Change operation when --only is specified

### ISSUE THREAD

**Issue by herb-kuta-lge** [ros-infrastructure/superflore#224]
The files under `conf` and `files` created by **superflore-gen-oe-recipes** are only useful when all of the recipes for a ROS distro are being generated => don't generate them when `--only` is specified.

Use a slighly different commit message when `--only` is specified.

Don't attempt a commit if there are no changes.

**Comment by shr-project** [comment]
Fixed by https://github.com/ros-infrastructure/superflore/pull/233
