### ISSUE TITLE
Use "recipe"/"ebuild" instead of "installer" in log messages

### ISSUE THREAD

**Issue by herb-kuta-lge** [ros-infrastructure/superflore#226]
The term "installer" doesn't make any sense in the context of OpenEmbedded; what superflore-gen-oe-recipes generates are recipes.

**Comment by allenh1** [comment]
@herb-kuta-lge I think I chose "installer" because it seemed the most neutral. At this point, however, it feels more misleading.

Gentoo should be changed to "ebuild" as well.

**Comment by shr-project** [comment]
Fixed by https://github.com/ros-infrastructure/superflore/pull/243
