### ISSUE TITLE
Change use of # in generated commit messages to ==... or --... on the next line

### ISSUE THREAD

**Issue by herb-kuta-lge** [ros-infrastructure/superflore#228]
**superflore** currently generates commit messages that contain lines starting with the markdown header indicator `#`. However, commit message lines that start with `#` are considered comments when amending a commit and are removed unless the user remembers to quote them. Prevent these lines from accidentally being dropped by using the alternate form of header indication: a line starting with `=`-s or `-`-s underneath the header text.

**Comment by allenh1** [comment]
> However, commit message lines that start with # are considered comments when amending a commit and are removed unless the user remembers to quote them. 

Hm... Yeah, that's definitely not so good. Thanks for catching this!

**Comment by herb-kuta-lge** [comment]
Resolved by #236.
