### ISSUE TITLE
Allow the timestamp associated with the superflore run to be overridden

### ISSUE THREAD

**Issue by herb-kuta-lge** [ros-infrastructure/superflore#231]
Revision 43 of [Superflore OE Recipe Generation Scheme](https://github.com/ros/meta-ros/wiki/Superflore-OE-Recipe-Generation-Scheme) requires that the datetime of a commit be used for the timestamp when generating OpenEmbedded recipes instead of "now". Implement this by using the value of the environment variable `SUPERFLORE_GENERATION_DATETIME` for the timestamp if it is set.

**Comment by shr-project** [comment]
Fixed by https://github.com/ros-infrastructure/superflore/pull/238
