### ISSUE TITLE
Allow to re-generate the recipes without creating new branch

### ISSUE THREAD

**Issue by shr-project** [ros-infrastructure/superflore#248]
In some work flows it's more convenient to e.g. run superflore multiple times for different ROS distributions and then submit it all from one branch (instead of each run creating new branch) or running superflore during interactive rebase of some other changes, where creating new branch during rebase actually breaks the flow.

Add --no-branch parameter to just create new commit in current branch instead of new commit in new branch with generated name.

**Comment by allenh1** [comment]
@shr-project that sounds reasonable to me! I've definitely been annoyed with it working with Gentoo before.
