### ISSUE TITLE
Release Version 0.3.3

### ISSUE THREAD

**Issue by herb-kuta-lge** [ros-infrastructure/superflore#283]
@allenh1 Would it be possible for you to release a new version of **superflore** now? Or do you want to wait for #282 to be completed?

**Comment by allenh1** [comment]
I'm not sure. @nuclearsandwich do you have any opinions on this?

**Comment by allenh1** [comment]
@nuclearsandwich friendly ping

**Comment by tfoote** [comment]
I wouldn't worry about waiting for the workflow before making the release.

**Comment by herb-kuta-lge** [comment]
@allenh1 < We've been waiting for you to do this. Have you been waiting for us to do it?

**Comment by allenh1** [comment]
@herb-kuta-lge My bad, it completely slipped my mind. I'll do this soon (and don't be afraid to remind me if I fail to ;)).

**Comment by shr-project** [comment]
@allenh1 gentle ping again, I might be working on updating superflore to generate new syntax for OE recipes soon to match:
https://lists.openembedded.org/g/openembedded-architecture/message/1260
https://lists.openembedded.org/g/openembedded-architecture/message/1279
https://lists.openembedded.org/g/openembedded-architecture/message/1291
and it would be great to have a release with the old syntax first.
