### ISSUE TITLE
Use Rosdep

### ISSUE THREAD

**Issue by allenh1** [ros-infrastructure/superflore#42]
Instead of fetching the yaml files from rosdistro, it would be much better to use `rosdep` for satisfying dependencies.

Tasks:
---------
 * [ ] Add Open Embedded support to Rosdep (allenh1/rosdep#1)
 * [ ] Initialize dependencies for Open Embedded into rosdistro
 * [x] Use rosdep to resolve dependencies for Ebuilds #58 
 * [ ] Use rosdep to resolve dependencies for Open Embedded builds

**Comment by allenh1** [comment]
This should probably be the next target.

**Comment by andre-rosa** [comment]
@allenh1 << Was this closed by #168 ?

**Comment by allenh1** [comment]
> @allenh1 << Was this closed by #168 ?

@andre-rosa It would seem so! Thanks for digging this up.
