### ISSUE TITLE
Add stdeb.cfg to support building debian packages

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/superflore#65]
Here's an example: https://github.com/ros-infrastructure/rosdep/blob/master/stdeb.cfg

We talked about only targeting python3

Make sure to call out git explicitly as a dependency. I ran into that here: https://gist.github.com/tfoote/4fff504f608ad45cf3e897cd2186025b

**Comment by allenh1** [comment]
Resolved by #133.
