### ISSUE TITLE
Replace custom Docker class with upstream docker library

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/superflore#66]
There's a docker python module that implements run etc. 

https://pypi.python.org/pypi/docker

Reusing the upstream module will likely be more robust in the long term. However, note that there are some very different versions available currently on common platforms. And a large API change in version 2.0

**Comment by allenh1** [comment]
> Reusing the upstream module will likely be more robust in the long term.

Sounds like a good idea to me!

**Comment by allenh1** [comment]
@tfoote PR is up! I just swapped out the subprocess calls to use the sdk.
