### ISSUE TITLE
2FA breaks everything

### ISSUE THREAD

**Issue by allenh1** [ros-infrastructure/superflore#67]
After updating my GitHib account to two-factor authentication, Superflore couldn't file pull requests in the usual fashion.

**Comment by tfoote** [comment]
You need to setup an oauth token and use it in the same way as bloom: http://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization

**Comment by allenh1** [comment]
Temporary Fix (before I actually integrate the OAth stuff):

Make an oath token and replace the password in the `.netrc` file with the token you get back.
