### ISSUE TITLE
Handle multiple packages while parsing

### ISSUE THREAD

**Issue by allenh1** [ros-infrastructure/superflore#7]
Things like [this](https://github.com/ros/rosdistro/pull/15208/files#diff-acba1c75aeaa27ae4af7a5e0a5b78c08R3510) need to be handled.

**Comment by Alessandro-Barbieri** [comment]
Using rosdep can solve this issue?

**Comment by allenh1** [comment]
I think so. I've already started a ticket on that topic: #42.
